version: '3.9'
services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    container_name: 'zero'
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - 3000:3000
    command: npm run start:dev
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: zero_db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - 5431:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
